import { Router } from "express";
import { requireAuth } from "../lib/auth.js";

// Which structural yardstick the scoring model should hold this prompt to on
// the structure dimension. Prompt category alone is not a reliable signal —
// e.g. "Motivation" and "Influence" appear in both a retrospective story
// ("tell me about a time you influenced someone") and a live, present-tense
// ask ("make cross-team cooperation happen") — so this is tagged explicitly
// per prompt rather than derived from category or free-text pattern matching.
//
// - story:          retrospective behavioural answer (STAR/SCR); a missing
//                    result is a real gap.
// - narrative:       self-introduction / background walkthrough; expects a
//                    Past → Present → Future arc with a forward-looking
//                    close, not a resolved outcome.
// - vision:          future-facing aspiration; a forward-looking goal
//                    statement IS the correct close — do not demand a
//                    completed proof point.
// - rationale:       direct-answer / self-assessment question (motivation,
//                    weakness, opinion); PREP-style point-first reasoning is
//                    expected, not STAR/SCR.
// - recommendation:  live communication of a decision, update, pitch, or
//                    pushback; SCR/Pyramid resolution is genuinely expected.
// - resilience:      an ongoing response to a recent setback; "what I'm
//                    doing about it now" is a valid close — a fully resolved
//                    happy outcome should not be demanded.
// - inspiration:     a rallying/motivational address; expects an emotional
//                    throughline and a call to action, not SCR.
export type StructureFamily =
  | "story"
  | "narrative"
  | "vision"
  | "rationale"
  | "recommendation"
  | "resilience"
  | "inspiration";

export interface Prompt {
  id: string;
  category: string;
  context: string;
  text: string;
  recommendedDurationSeconds: number;
  sector?: string;
  structureFamily: StructureFamily;
  // Present only on prompts drawn from a specific named company's own
  // question bank (see company_knowledge_base.json). Absent means this is a
  // generic sector-level prompt. Kept separate from `sector` so a
  // company-tagged prompt can still be filtered into the right sector pool
  // as a fallback if no company match applies.
  company?: string;
  peiDimension?: string;
}

export const PROMPTS: Prompt[] = [

  // ── WORKPLACE PROMPTS ─────────────────────────────────────────────────────

  {
    id: "W1",
    structureFamily: "narrative",
    category: "Introduction",
    context: "Stakeholder Update",
    text: "Introduce yourself to a new team or stakeholder group. Establish who you are, what you bring, and why it matters to them.",
    recommendedDurationSeconds: 60,
  },
  {
    id: "W2",
    structureFamily: "narrative",
    category: "Introduction",
    context: "Stakeholder Update",
    text: "You are at a senior professional event. Someone asks what you do. Make it memorable in under a minute.",
    recommendedDurationSeconds: 60,
  },
  {
    id: "W3",
    structureFamily: "narrative",
    category: "Introduction",
    context: "Stakeholder Update",
    text: "You are meeting a new client for the first time. Introduce yourself and establish your credibility without overselling.",
    recommendedDurationSeconds: 60,
  },
  {
    id: "W4",
    structureFamily: "recommendation",
    category: "Persuasion",
    context: "Formal Presentation",
    text: "Make the case to a skeptical senior leader for a resource, investment, or change your work requires.",
    recommendedDurationSeconds: 90,
  },
  {
    id: "W5",
    structureFamily: "recommendation",
    category: "Persuasion",
    context: "Formal Presentation",
    text: "Pitch an idea you believe in to a room that has not asked for it and may push back.",
    recommendedDurationSeconds: 90,
  },
  {
    id: "W6",
    structureFamily: "recommendation",
    category: "Persuasion",
    context: "Stakeholder Update",
    text: "Make the case for why you should lead an upcoming high-visibility opportunity.",
    recommendedDurationSeconds: 90,
  },
  {
    id: "W7",
    structureFamily: "recommendation",
    category: "Persuasion",
    context: "Stakeholder Update",
    text: "Someone whose support you need is not yet convinced by your approach. Bring them along — without authority, without pressure.",
    recommendedDurationSeconds: 90,
  },
  {
    id: "W8",
    structureFamily: "vision",
    category: "Vision",
    context: "Formal Presentation",
    text: "Describe what success looks like in your current role or team in three years — for you, for the people around you, and for the organization.",
    recommendedDurationSeconds: 120,
  },
  {
    id: "W9",
    structureFamily: "vision",
    category: "Vision",
    context: "Stakeholder Update",
    text: "Describe where you want to be professionally in three years and what you are doing right now to get there.",
    recommendedDurationSeconds: 120,
  },
  {
    id: "W10",
    structureFamily: "recommendation",
    category: "Feedback",
    context: "Difficult Conversation",
    text: "Deliver constructive feedback to someone who is capable and high-performing but has missed an important commitment.",
    recommendedDurationSeconds: 90,
  },
  {
    id: "W11",
    structureFamily: "rationale",
    category: "Feedback",
    context: "Difficult Conversation",
    text: "You have just received critical feedback that stings. Respond to it out loud — show that you have heard it, processed it, and know what to do with it.",
    recommendedDurationSeconds: 90,
  },
  {
    id: "W12",
    structureFamily: "recommendation",
    category: "Difficult Conversation",
    context: "Difficult Conversation",
    text: "A colleague's behavior in a recent meeting created a problem for the team. Raise it with them directly and constructively.",
    recommendedDurationSeconds: 90,
  },
  {
    id: "W13",
    structureFamily: "recommendation",
    category: "Difficult Conversation",
    context: "Difficult Conversation",
    text: "Push back on a decision made by someone more senior than you. Be clear, be direct, and stay respectful.",
    recommendedDurationSeconds: 90,
  },
  {
    id: "W14",
    structureFamily: "recommendation",
    category: "Difficult Conversation",
    context: "Difficult Conversation",
    text: "You need to tell someone their role is changing in a way they will not welcome. Deliver the message with clarity and care.",
    recommendedDurationSeconds: 90,
  },
  {
    id: "W15",
    structureFamily: "recommendation",
    category: "Difficult Conversation",
    context: "Difficult Conversation",
    text: "A team member is consistently underperforming. Begin the conversation that needs to happen.",
    recommendedDurationSeconds: 90,
  },
  {
    id: "W16",
    structureFamily: "recommendation",
    category: "Crisis",
    context: "Formal Presentation",
    text: "Something has gone wrong on a project or initiative you are responsible for. Address the people involved — name what happened, take accountability, and lay out what comes next.",
    recommendedDurationSeconds: 120,
  },
  {
    id: "W17",
    structureFamily: "recommendation",
    category: "Crisis",
    context: "Stakeholder Update",
    text: "A senior stakeholder has just heard about a problem before you could brief them. Get ahead of it now.",
    recommendedDurationSeconds: 90,
  },
  {
    id: "W18",
    structureFamily: "recommendation",
    category: "Data",
    context: "Formal Presentation",
    text: "Present the three most important findings from a piece of work to a leadership audience who care about implications, not methodology.",
    recommendedDurationSeconds: 90,
  },
  {
    id: "W19",
    structureFamily: "recommendation",
    category: "Data",
    context: "Stakeholder Update",
    text: "Explain a complex idea in your field to someone intelligent who knows nothing about it. Make it land in under two minutes.",
    recommendedDurationSeconds: 90,
  },
  {
    id: "W20",
    structureFamily: "recommendation",
    category: "Negotiation",
    context: "Difficult Conversation",
    text: "Negotiate a change — to scope, timeline, or terms — with someone who is resistant.",
    recommendedDurationSeconds: 90,
  },
  {
    id: "W21",
    structureFamily: "recommendation",
    category: "Negotiation",
    context: "Difficult Conversation",
    text: "Your counterpart has just pushed back hard on your position. Hold your ground without creating conflict.",
    recommendedDurationSeconds: 90,
  },
  {
    id: "W22",
    structureFamily: "inspiration",
    category: "Inspiration",
    context: "High Energy",
    text: "The quarter ahead is demanding and the team knows it. Say something that makes them want to show up fully.",
    recommendedDurationSeconds: 90,
  },
  {
    id: "W23",
    structureFamily: "recommendation",
    category: "Stakeholder Update",
    context: "Stakeholder Update",
    text: "Brief a senior stakeholder on the current status of a high-priority piece of work — include one risk you are actively managing.",
    recommendedDurationSeconds: 90,
  },
  {
    id: "W24",
    structureFamily: "recommendation",
    category: "Stakeholder Update",
    context: "Stakeholder Update",
    text: "Update a skeptical client or stakeholder on a project that has fallen behind. Be direct and maintain their confidence.",
    recommendedDurationSeconds: 90,
  },
  {
    id: "W25",
    structureFamily: "recommendation",
    category: "Stakeholder Update",
    context: "Stakeholder Update",
    text: "Update your manager on a project that has hit an unexpected obstacle. Come with the problem and a path forward.",
    recommendedDurationSeconds: 90,
  },
  {
    id: "W26",
    structureFamily: "recommendation",
    category: "Influence",
    context: "Stakeholder Update",
    text: "You need cross-team cooperation on something that is not anyone else's priority. Make the ask in a way that gets a yes.",
    recommendedDurationSeconds: 90,
  },
  {
    id: "W27",
    structureFamily: "resilience",
    category: "Resilience",
    context: "Difficult Conversation",
    text: "You have just been given a setback — a rejected proposal, a missed opportunity, a difficult outcome. Speak to what happened and what you are doing with it.",
    recommendedDurationSeconds: 90,
  },
  {
    id: "W28",
    structureFamily: "rationale",
    category: "Impromptu",
    context: "Impromptu",
    text: "A senior leader has just asked your opinion on something you were not expecting to be asked about. Give a clear, considered view in 90 seconds.",
    recommendedDurationSeconds: 90,
  },
  {
    id: "W29",
    structureFamily: "rationale",
    category: "Impromptu",
    context: "Impromptu",
    text: "You have been asked, without warning, to speak for two minutes on the biggest challenge facing your organization or industry right now. Begin.",
    recommendedDurationSeconds: 120,
  },
  {
    id: "W30",
    structureFamily: "rationale",
    category: "Impromptu",
    context: "Impromptu",
    text: "You have 60 seconds in a lift with the most senior person in your field. Make it count.",
    recommendedDurationSeconds: 60,
  },

  // ── INTERVIEW — UNIVERSAL ─────────────────────────────────────────────────

  {
    id: "I1",
    structureFamily: "narrative",
    category: "Opening",
    context: "Impromptu",
    text: "Tell me about yourself.",
    recommendedDurationSeconds: 90,
    sector: "all",
  },
  {
    id: "I2",
    structureFamily: "narrative",
    category: "Opening",
    context: "Impromptu",
    text: "Walk me through your background and what has brought you to this point.",
    recommendedDurationSeconds: 90,
    sector: "all",
  },
  {
    id: "I3",
    structureFamily: "story",
    category: "Achievement",
    context: "Impromptu",
    text: "Tell me about your most significant professional achievement and why it stands out.",
    recommendedDurationSeconds: 120,
    sector: "all",
  },
  {
    id: "I4",
    structureFamily: "story",
    category: "Leadership",
    context: "Impromptu",
    text: "Tell me about a time you led through significant uncertainty or ambiguity.",
    recommendedDurationSeconds: 120,
    sector: "all",
  },
  {
    id: "I5",
    structureFamily: "story",
    category: "Leadership",
    context: "Impromptu",
    text: "Tell me about a time you led a team through a difficult situation with no clear playbook.",
    recommendedDurationSeconds: 120,
    sector: "all",
  },
  {
    id: "I6",
    structureFamily: "story",
    category: "Influence",
    context: "Impromptu",
    text: "Tell me about a time you had to influence someone — a peer, a senior leader, or a client — who initially did not agree with you.",
    recommendedDurationSeconds: 120,
    sector: "all",
  },
  {
    id: "I7",
    structureFamily: "story",
    category: "Failure",
    context: "Impromptu",
    text: "Tell me about a time you failed. What happened, what did you do, and what did you take from it?",
    recommendedDurationSeconds: 120,
    sector: "all",
  },
  {
    id: "I8",
    structureFamily: "story",
    category: "Conflict",
    context: "Impromptu",
    text: "Tell me about a time you had a disagreement with a colleague or manager. How did you handle it?",
    recommendedDurationSeconds: 120,
    sector: "all",
  },
  {
    id: "I9",
    structureFamily: "story",
    category: "Feedback",
    context: "Impromptu",
    text: "Tell me about a time you received critical feedback. How did you respond to it?",
    recommendedDurationSeconds: 120,
    sector: "all",
  },
  {
    id: "I10",
    structureFamily: "story",
    category: "Pressure",
    context: "Impromptu",
    text: "Tell me about a time you had to deliver something important under significant time pressure. What did you prioritize and what did you let go?",
    recommendedDurationSeconds: 120,
    sector: "all",
  },
  {
    id: "I11",
    structureFamily: "story",
    category: "Adaptability",
    context: "Impromptu",
    text: "Tell me about a time you had to adapt quickly to a significant and unexpected change.",
    recommendedDurationSeconds: 120,
    sector: "all",
  },
  {
    id: "I12",
    structureFamily: "story",
    category: "Values",
    context: "Impromptu",
    text: "Tell me about a time you had to make a decision that involved a genuine ethical or values tension. What did you do?",
    recommendedDurationSeconds: 120,
    sector: "all",
  },
  {
    id: "I13",
    structureFamily: "rationale",
    category: "Motivation",
    context: "Impromptu",
    text: "Why this organization? Why this role? Why now?",
    recommendedDurationSeconds: 90,
    sector: "all",
  },
  {
    id: "I14",
    structureFamily: "rationale",
    category: "Weakness",
    context: "Impromptu",
    text: "What is your greatest professional weakness and what are you actively doing about it?",
    recommendedDurationSeconds: 90,
    sector: "all",
  },
  {
    id: "I15",
    structureFamily: "rationale",
    category: "AI",
    context: "Impromptu",
    text: "How do you use AI in your work? Give a specific example.",
    recommendedDurationSeconds: 90,
    sector: "all",
  },
  {
    id: "I16",
    structureFamily: "rationale",
    category: "Impromptu",
    context: "Impromptu",
    text: "You have been asked, without warning, to speak for 90 seconds on the most important lesson your career has taught you. No preparation. Begin.",
    recommendedDurationSeconds: 90,
    sector: "all",
  },

  // ── INTERVIEW — CONSULTING ────────────────────────────────────────────────

  {
    id: "C1",
    structureFamily: "rationale",
    category: "Motivation",
    context: "Impromptu",
    text: "Why consulting? Why this firm specifically? Why now in your career?",
    recommendedDurationSeconds: 90,
    sector: "consulting",
  },
  {
    id: "C2",
    structureFamily: "story",
    category: "Influence",
    context: "Impromptu",
    text: "Tell me about a time you had to persuade a skeptical senior stakeholder to accept a recommendation they initially resisted.",
    recommendedDurationSeconds: 120,
    sector: "consulting",
  },
  {
    id: "C3",
    structureFamily: "story",
    category: "Leadership",
    context: "Impromptu",
    text: "Tell me about a time you led a team through a situation with no clear precedent or playbook.",
    recommendedDurationSeconds: 120,
    sector: "consulting",
  },
  {
    id: "C4",
    structureFamily: "story",
    category: "Difficult Conversation",
    context: "Impromptu",
    text: "Tell me about a time you delivered an unpopular recommendation. How did you communicate it and handle the pushback?",
    recommendedDurationSeconds: 120,
    sector: "consulting",
  },
  {
    id: "C5",
    structureFamily: "story",
    category: "Achievement",
    context: "Impromptu",
    text: "Describe a situation where your analysis fundamentally changed the direction of a project or engagement.",
    recommendedDurationSeconds: 120,
    sector: "consulting",
  },
  {
    id: "C6",
    structureFamily: "story",
    category: "Adaptability",
    context: "Impromptu",
    text: "Tell me about a time you had to learn an unfamiliar domain quickly and still deliver meaningful work.",
    recommendedDurationSeconds: 120,
    sector: "consulting",
  },
  {
    id: "C7",
    structureFamily: "story",
    category: "Difficult Conversation",
    context: "Impromptu",
    text: "Tell me about a time you had to say no — to a client, a senior colleague, or a stakeholder — and how you handled it.",
    recommendedDurationSeconds: 120,
    sector: "consulting",
  },
  {
    id: "C8",
    structureFamily: "story",
    category: "Pressure",
    context: "Impromptu",
    text: "Tell me about a time you worked under extreme pressure to deliver a high-quality output. What trade-offs did you make?",
    recommendedDurationSeconds: 120,
    sector: "consulting",
  },
  {
    id: "C9",
    structureFamily: "story",
    category: "Failure",
    context: "Impromptu",
    text: "Tell me about a time your recommendation turned out to be wrong. How did you handle it?",
    recommendedDurationSeconds: 120,
    sector: "consulting",
  },
  {
    id: "C10",
    structureFamily: "rationale",
    category: "Weakness",
    context: "Impromptu",
    text: "What is your greatest weakness and what are you actively doing about it?",
    recommendedDurationSeconds: 90,
    sector: "consulting",
  },

  // ── INTERVIEW — MCKINSEY & COMPANY (PEI question bank) ───────────────────
  // Tagged with company + peiDimension so record.tsx can prefer these over
  // the generic consulting pool above when McKinsey is the active company.
  // See company_knowledge_base.json for the evidence/confidence behind each
  // question — several of these are prep-industry consensus, not verified
  // firm-issued wording, and are treated as such in scoring guidance.
  {
    id: "MCK1",
    structureFamily: "story",
    category: "Connection",
    context: "Impromptu",
    text: "Explain a challenging situation you encountered when working with someone with an opposing opinion.",
    recommendedDurationSeconds: 120,
    sector: "consulting",
    company: "McKinsey & Company",
    peiDimension: "Connection",
  },
  {
    id: "MCK2",
    structureFamily: "story",
    category: "Connection",
    context: "Impromptu",
    text: "Tell me about a time you had to convince someone to change their mind.",
    recommendedDurationSeconds: 120,
    sector: "consulting",
    company: "McKinsey & Company",
    peiDimension: "Connection",
  },
  {
    id: "MCK3",
    structureFamily: "story",
    category: "Drive",
    context: "Impromptu",
    text: "Talk about a time when you worked hard to achieve excellence in particularly tough circumstances.",
    recommendedDurationSeconds: 120,
    sector: "consulting",
    company: "McKinsey & Company",
    peiDimension: "Drive",
  },
  {
    id: "MCK4",
    structureFamily: "story",
    category: "Drive",
    context: "Impromptu",
    text: "Tell me about a time you pushed through a significant obstacle to get something done.",
    recommendedDurationSeconds: 120,
    sector: "consulting",
    company: "McKinsey & Company",
    peiDimension: "Drive",
  },
  {
    id: "MCK5",
    structureFamily: "story",
    category: "Leadership",
    context: "Impromptu",
    text: "Share an example where you worked effectively with people with different backgrounds despite challenges.",
    recommendedDurationSeconds: 120,
    sector: "consulting",
    company: "McKinsey & Company",
    peiDimension: "Leadership",
  },
  {
    id: "MCK6",
    structureFamily: "story",
    category: "Leadership",
    context: "Impromptu",
    text: "Provide an example of when you had to demonstrate leadership and direction under ambiguous circumstances.",
    recommendedDurationSeconds: 120,
    sector: "consulting",
    company: "McKinsey & Company",
    peiDimension: "Leadership",
  },
  {
    id: "MCK7",
    structureFamily: "story",
    category: "Growth",
    context: "Impromptu",
    text: "Revisit a time when you had to rapidly learn something new to tackle a challenging situation.",
    recommendedDurationSeconds: 120,
    sector: "consulting",
    company: "McKinsey & Company",
    peiDimension: "Growth",
  },
  {
    id: "MCK8",
    structureFamily: "story",
    category: "Growth",
    context: "Impromptu",
    text: "What was your biggest failure?",
    recommendedDurationSeconds: 120,
    sector: "consulting",
    company: "McKinsey & Company",
    peiDimension: "Growth",
  },
  {
    id: "MCK9",
    structureFamily: "narrative",
    category: "Introduction",
    context: "Impromptu",
    text: "Tell me about yourself.",
    recommendedDurationSeconds: 90,
    sector: "consulting",
    company: "McKinsey & Company",
  },
  {
    id: "MCK10",
    structureFamily: "rationale",
    category: "Motivation",
    context: "Impromptu",
    text: "Why McKinsey? Why consulting?",
    recommendedDurationSeconds: 90,
    sector: "consulting",
    company: "McKinsey & Company",
  },
  {
    id: "MCK11",
    structureFamily: "rationale",
    category: "Self-Assessment",
    context: "Impromptu",
    text: "What would you say is your greatest strength?",
    recommendedDurationSeconds: 90,
    sector: "consulting",
    company: "McKinsey & Company",
  },
  {
    id: "MCK12",
    structureFamily: "rationale",
    category: "Self-Assessment",
    context: "Impromptu",
    text: "What would you say is your greatest weakness?",
    recommendedDurationSeconds: 90,
    sector: "consulting",
    company: "McKinsey & Company",
  },

  // ── INTERVIEW — BAIN & COMPANY ────────────────────────────────────────────
  // No peiDimension tagged here deliberately: unlike McKinsey's PEI or
  // Amazon's LPs, Bain publishes no named/scored dimensions — the
  // "dimensions" in company_knowledge_base.json are an inferred synthesis,
  // not a real Bain framework. Tagging them here would make the session-
  // reveal feature claim a formal category that doesn't exist, so these
  // prompts carry `company` only and the reveal line stays silent for them.
  {
    id: "BAIN1",
    structureFamily: "rationale",
    category: "Motivation",
    context: "Impromptu",
    text: "Why do you want to work at Bain?",
    recommendedDurationSeconds: 90,
    sector: "consulting",
    company: "Bain & Company",
  },
  {
    id: "BAIN2",
    structureFamily: "narrative",
    category: "Introduction",
    context: "Impromptu",
    text: "Tell me about yourself.",
    recommendedDurationSeconds: 90,
    sector: "consulting",
    company: "Bain & Company",
  },
  {
    id: "BAIN3",
    structureFamily: "narrative",
    category: "Introduction",
    context: "Impromptu",
    text: "Walk me through your resume.",
    recommendedDurationSeconds: 90,
    sector: "consulting",
    company: "Bain & Company",
  },
  {
    id: "BAIN4",
    structureFamily: "rationale",
    category: "Motivation",
    context: "Impromptu",
    text: "Why consulting?",
    recommendedDurationSeconds: 90,
    sector: "consulting",
    company: "Bain & Company",
  },
  {
    id: "BAIN5",
    structureFamily: "rationale",
    category: "Self-Assessment",
    context: "Impromptu",
    text: "What's your weakness?",
    recommendedDurationSeconds: 90,
    sector: "consulting",
    company: "Bain & Company",
  },
  {
    id: "BAIN6",
    structureFamily: "rationale",
    category: "Self-Assessment",
    context: "Impromptu",
    text: "What's your strongest skill?",
    recommendedDurationSeconds: 90,
    sector: "consulting",
    company: "Bain & Company",
  },
  {
    id: "BAIN7",
    structureFamily: "story",
    category: "Leadership",
    context: "Impromptu",
    text: "Tell me about a leadership experience.",
    recommendedDurationSeconds: 120,
    sector: "consulting",
    company: "Bain & Company",
  },
  {
    id: "BAIN8",
    structureFamily: "story",
    category: "Teamwork",
    context: "Impromptu",
    text: "Tell me about your favorite team you've worked with, and what made it work.",
    recommendedDurationSeconds: 120,
    sector: "consulting",
    company: "Bain & Company",
  },

  // ── INTERVIEW — BOSTON CONSULTING GROUP ──────────────────────────────────
  // BCG publishes a real 5-quality framework (unlike Bain), so these carry
  // peiDimension the same way McKinsey/Amazon do, enabling the post-scoring
  // dimension reveal.
  {
    id: "BCG1",
    structureFamily: "story",
    category: "Integrity",
    context: "Impromptu",
    text: "Tell me about a time when you were wrong and had to admit it.",
    recommendedDurationSeconds: 120,
    sector: "consulting",
    company: "Boston Consulting Group",
    peiDimension: "Integrity",
  },
  {
    id: "BCG2",
    structureFamily: "story",
    category: "Intellectual Curiosity",
    context: "Impromptu",
    text: "Tell me about a time you had to learn something quickly.",
    recommendedDurationSeconds: 120,
    sector: "consulting",
    company: "Boston Consulting Group",
    peiDimension: "Intellectual Curiosity",
  },
  {
    id: "BCG3",
    structureFamily: "rationale",
    category: "Intellectual Curiosity",
    context: "Impromptu",
    text: "What's a technology that's changing the world around you that you find interesting, and why?",
    recommendedDurationSeconds: 90,
    sector: "consulting",
    company: "Boston Consulting Group",
    peiDimension: "Intellectual Curiosity",
  },
  {
    id: "BCG4",
    structureFamily: "rationale",
    category: "Creative Thinking",
    context: "Impromptu",
    text: "If you were to start a business, what would it be, and why?",
    recommendedDurationSeconds: 90,
    sector: "consulting",
    company: "Boston Consulting Group",
    peiDimension: "Creative Thinking",
  },
  {
    id: "BCG5",
    structureFamily: "story",
    category: "Collaborative Mindset",
    context: "Impromptu",
    text: "Tell me about a time you motivated team members.",
    recommendedDurationSeconds: 120,
    sector: "consulting",
    company: "Boston Consulting Group",
    peiDimension: "Collaborative Mindset",
  },
  {
    id: "BCG6",
    structureFamily: "story",
    category: "Collaborative Mindset",
    context: "Impromptu",
    text: "Tell me about a time you disagreed with a senior person.",
    recommendedDurationSeconds: 120,
    sector: "consulting",
    company: "Boston Consulting Group",
    peiDimension: "Collaborative Mindset",
  },
  {
    id: "BCG7",
    structureFamily: "story",
    category: "Drive",
    context: "Impromptu",
    text: "What was your most significant accomplishment, and how did you achieve it?",
    recommendedDurationSeconds: 120,
    sector: "consulting",
    company: "Boston Consulting Group",
    peiDimension: "Drive",
  },
  {
    id: "BCG8",
    structureFamily: "story",
    category: "Drive",
    context: "Impromptu",
    text: "Tell me about a time you failed as a leader.",
    recommendedDurationSeconds: 120,
    sector: "consulting",
    company: "Boston Consulting Group",
    peiDimension: "Drive",
  },
  {
    id: "BCG9",
    structureFamily: "narrative",
    category: "Introduction",
    context: "Impromptu",
    text: "Tell me about yourself.",
    recommendedDurationSeconds: 90,
    sector: "consulting",
    company: "Boston Consulting Group",
  },
  {
    id: "BCG10",
    structureFamily: "rationale",
    category: "Motivation",
    context: "Impromptu",
    text: "Why do you want to work at BCG?",
    recommendedDurationSeconds: 90,
    sector: "consulting",
    company: "Boston Consulting Group",
  },
  {
    id: "BCG11",
    structureFamily: "rationale",
    category: "Self-Assessment",
    context: "Impromptu",
    text: "What are your strengths and weaknesses?",
    recommendedDurationSeconds: 90,
    sector: "consulting",
    company: "Boston Consulting Group",
  },

  // ── INTERVIEW — OLIVER WYMAN ──────────────────────────────────────────────
  // No peiDimension here, same reasoning as Bain: OW publishes company
  // values but explicitly does not say interviews are scored against them —
  // even weaker footing than Bain's named "qualities it evaluates" in
  // hiring. Tagged with company only, merged into the generic consulting
  // pool via COMPANIES_WITHOUT_FIXED_FRAMEWORK in record.tsx.
  {
    id: "OW1",
    structureFamily: "rationale",
    category: "Motivation",
    context: "Impromptu",
    text: "Why Oliver Wyman?",
    recommendedDurationSeconds: 90,
    sector: "consulting",
    company: "Oliver Wyman",
  },
  {
    id: "OW2",
    structureFamily: "rationale",
    category: "Motivation",
    context: "Impromptu",
    text: "Why consulting?",
    recommendedDurationSeconds: 90,
    sector: "consulting",
    company: "Oliver Wyman",
  },
  {
    id: "OW3",
    structureFamily: "rationale",
    category: "Motivation",
    context: "Impromptu",
    text: "Why Oliver Wyman rather than one of the larger strategy firms?",
    recommendedDurationSeconds: 90,
    sector: "consulting",
    company: "Oliver Wyman",
  },
  {
    id: "OW4",
    structureFamily: "narrative",
    category: "Introduction",
    context: "Impromptu",
    text: "Tell me about yourself and your background.",
    recommendedDurationSeconds: 90,
    sector: "consulting",
    company: "Oliver Wyman",
  },
  {
    id: "OW5",
    structureFamily: "narrative",
    category: "Introduction",
    context: "Impromptu",
    text: "Walk me through your resume.",
    recommendedDurationSeconds: 90,
    sector: "consulting",
    company: "Oliver Wyman",
  },
  {
    id: "OW6",
    structureFamily: "story",
    category: "Impact",
    context: "Impromptu",
    text: "Tell me about a time you did more than what you were asked to do.",
    recommendedDurationSeconds: 120,
    sector: "consulting",
    company: "Oliver Wyman",
  },
  {
    id: "OW7",
    structureFamily: "story",
    category: "Achievement",
    context: "Impromptu",
    text: "Tell me about something you're proud of.",
    recommendedDurationSeconds: 120,
    sector: "consulting",
    company: "Oliver Wyman",
  },

  // ── INTERVIEW — BANKING & FINANCE ─────────────────────────────────────────

  {
    id: "B1",
    structureFamily: "rationale",
    category: "Motivation",
    context: "Impromptu",
    text: "Why this firm? Why this division? Why now?",
    recommendedDurationSeconds: 90,
    sector: "banking",
  },
  {
    id: "B2",
    structureFamily: "story",
    category: "Achievement",
    context: "Impromptu",
    text: "Walk me through the most commercially significant piece of work or deal you have been part of. What was at stake and what was your specific role?",
    recommendedDurationSeconds: 120,
    sector: "banking",
  },
  {
    id: "B3",
    structureFamily: "story",
    category: "Judgment",
    context: "Impromptu",
    text: "Tell me about a time you identified a significant risk or problem before others did. What did you do?",
    recommendedDurationSeconds: 120,
    sector: "banking",
  },
  {
    id: "B4",
    structureFamily: "story",
    category: "Pressure",
    context: "Impromptu",
    text: "Tell me about a time you had to maintain quality and precision under conditions that were actively working against you.",
    recommendedDurationSeconds: 120,
    sector: "banking",
  },
  {
    id: "B5",
    structureFamily: "story",
    category: "Achievement",
    context: "Impromptu",
    text: "Tell me about a time you had to stand out in an environment where everyone around you was exceptional. What did you do differently?",
    recommendedDurationSeconds: 120,
    sector: "banking",
  },
  {
    id: "B6",
    structureFamily: "story",
    category: "Communication",
    context: "Impromptu",
    text: "Tell me about a time you had to present something complex to a non-specialist audience. How did you approach it?",
    recommendedDurationSeconds: 120,
    sector: "banking",
  },
  {
    id: "B7",
    structureFamily: "story",
    category: "Conflict",
    context: "Impromptu",
    text: "Tell me about a time you disagreed with a senior person. How did you handle it?",
    recommendedDurationSeconds: 120,
    sector: "banking",
  },
  {
    id: "B8",
    structureFamily: "story",
    category: "Difficult Conversation",
    context: "Impromptu",
    text: "Tell me about a time you had to hold your position under significant pressure from someone more senior.",
    recommendedDurationSeconds: 120,
    sector: "banking",
  },
  {
    id: "B9",
    structureFamily: "story",
    category: "Pressure",
    context: "Impromptu",
    text: "Tell me about a time you had to manage multiple competing high-priority demands simultaneously. How did you decide what to do first?",
    recommendedDurationSeconds: 120,
    sector: "banking",
  },
  {
    id: "B10",
    structureFamily: "rationale",
    category: "Motivation",
    context: "Impromptu",
    text: "What is it about finance and this specific firm that brings you here?",
    recommendedDurationSeconds: 90,
    sector: "banking",
  },

  // ── INTERVIEW — TECHNOLOGY ────────────────────────────────────────────────

  {
    id: "T1",
    structureFamily: "rationale",
    category: "Motivation",
    context: "Impromptu",
    text: "Why this company? What specifically draws you here over every other option?",
    recommendedDurationSeconds: 90,
    sector: "tech",
  },
  {
    id: "T2",
    structureFamily: "story",
    category: "Ownership",
    context: "Impromptu",
    text: "Tell me about a time you took ownership of a problem that was not technically your responsibility.",
    recommendedDurationSeconds: 120,
    sector: "tech",
  },
  {
    id: "T3",
    structureFamily: "story",
    category: "Influence",
    context: "Impromptu",
    text: "Tell me about a time you had to influence a major decision without formal authority. How did you get buy-in?",
    recommendedDurationSeconds: 120,
    sector: "tech",
  },
  {
    id: "T4",
    structureFamily: "story",
    category: "Data",
    context: "Impromptu",
    text: "Tell me about a time you used data to drive a significant decision or fundamentally change a direction.",
    recommendedDurationSeconds: 120,
    sector: "tech",
  },
  {
    id: "T5",
    structureFamily: "story",
    category: "Judgment",
    context: "Impromptu",
    text: "Tell me about a time you made a call with significant uncertainty and no consensus around you. How did you decide and how did you communicate it?",
    recommendedDurationSeconds: 120,
    sector: "tech",
  },
  {
    id: "T6",
    structureFamily: "story",
    category: "Adaptability",
    context: "Impromptu",
    text: "Tell me about a time you shipped something quickly and then iterated based on real feedback. What changed and what did you learn?",
    recommendedDurationSeconds: 120,
    sector: "tech",
  },
  {
    id: "T7",
    structureFamily: "story",
    category: "Failure",
    context: "Impromptu",
    text: "Tell me about a time you failed to deliver on something you committed to. What happened and what did you do differently?",
    recommendedDurationSeconds: 120,
    sector: "tech",
  },
  {
    id: "T8",
    structureFamily: "story",
    category: "Influence",
    context: "Impromptu",
    text: "Tell me about a time you had to align stakeholders with conflicting priorities around a single decision.",
    recommendedDurationSeconds: 120,
    sector: "tech",
  },
  {
    id: "T9",
    structureFamily: "story",
    category: "Achievement",
    context: "Impromptu",
    text: "Tell me about a time you built or launched something meaningful with limited resources or guidance.",
    recommendedDurationSeconds: 120,
    sector: "tech",
  },
  {
    id: "T10",
    structureFamily: "rationale",
    category: "AI",
    context: "Impromptu",
    text: "How do you use AI in your work? Give a specific example of where it helped and where you chose not to trust it.",
    recommendedDurationSeconds: 90,
    sector: "tech",
  },

  // ── INTERVIEW — GOOGLE (Googleyness & Leadership question bank) ──────────
  // 4 official behavioral themes tagged with peiDimension (full reveal
  // treatment). GOOG8 (Strategic Thinking) is a placeholder — the dimension
  // itself has zero candidate evidence of ever being asked, only named on
  // Google's own page; see company_knowledge_base.json. The two "Googleyness"
  // questions carry company only, no peiDimension — that term is explicitly
  // NOT on Google's official interview-prep page, so tagging it with a
  // dimension would misrepresent it as confirmed Google terminology in the
  // post-scoring reveal.
  {
    id: "GOOG1",
    structureFamily: "rationale",
    category: "Navigating Complexity and Ambiguity",
    context: "Impromptu",
    text: "How do you deal with ambiguous situations and problems?",
    recommendedDurationSeconds: 90,
    sector: "tech",
    company: "Google",
    peiDimension: "Navigating complexity and ambiguity",
  },
  {
    id: "GOOG2",
    structureFamily: "story",
    category: "Navigating Complexity and Ambiguity",
    context: "Impromptu",
    text: "Tell me about a time you had to make an important decision without having the full picture. What did you do, and how did it turn out?",
    recommendedDurationSeconds: 120,
    sector: "tech",
    company: "Google",
    peiDimension: "Navigating complexity and ambiguity",
  },
  {
    id: "GOOG3",
    structureFamily: "story",
    category: "Working with People and Teams",
    context: "Impromptu",
    text: "How would you address a conflict with someone you work with?",
    recommendedDurationSeconds: 120,
    sector: "tech",
    company: "Google",
    peiDimension: "Working with people and teams",
  },
  {
    id: "GOOG4",
    structureFamily: "rationale",
    category: "Working with People and Teams",
    context: "Impromptu",
    text: "What strategies would you use to influence teammates?",
    recommendedDurationSeconds: 90,
    sector: "tech",
    company: "Google",
    peiDimension: "Working with people and teams",
  },
  {
    id: "GOOG5",
    structureFamily: "story",
    category: "Working with People and Teams",
    context: "Impromptu",
    text: "Tell me about a time you drove collaboration across a team.",
    recommendedDurationSeconds: 120,
    sector: "tech",
    company: "Google",
    peiDimension: "Working with people and teams",
  },
  {
    id: "GOOG6",
    structureFamily: "story",
    category: "Leadership",
    context: "Impromptu",
    text: "How have you used your communication and decision-making skills to mobilize others, including when you weren't officially the leader?",
    recommendedDurationSeconds: 120,
    sector: "tech",
    company: "Google",
    peiDimension: "Leadership",
  },
  {
    id: "GOOG7",
    structureFamily: "story",
    category: "Leadership",
    context: "Impromptu",
    text: "Tell me about a time your actions had a positive impact on your team.",
    recommendedDurationSeconds: 120,
    sector: "tech",
    company: "Google",
    peiDimension: "Leadership",
  },
  {
    id: "GOOG8",
    structureFamily: "story",
    category: "Strategic Thinking",
    context: "Impromptu",
    text: "Tell me about a time you had to think several steps ahead to set a direction for your team or project.",
    recommendedDurationSeconds: 120,
    sector: "tech",
    company: "Google",
    peiDimension: "Strategic thinking",
  },
  {
    id: "GOOG9",
    structureFamily: "story",
    category: "General",
    context: "Impromptu",
    text: "A decision you have made in the past that you would change, and why.",
    recommendedDurationSeconds: 120,
    sector: "tech",
    company: "Google",
  },
  {
    id: "GOOG10",
    structureFamily: "rationale",
    category: "General",
    context: "Impromptu",
    text: "How would you respond to a customer who is offering you free tickets for a concert as an appreciation?",
    recommendedDurationSeconds: 90,
    sector: "tech",
    company: "Google",
  },
  {
    id: "GOOG11",
    structureFamily: "narrative",
    category: "Introduction",
    context: "Impromptu",
    text: "Tell me about yourself.",
    recommendedDurationSeconds: 90,
    sector: "tech",
    company: "Google",
  },
  {
    id: "GOOG12",
    structureFamily: "rationale",
    category: "AI",
    context: "Impromptu",
    text: "How do you use AI in your work?",
    recommendedDurationSeconds: 90,
    sector: "tech",
    company: "Google",
  },
  {
    id: "GOOG13",
    structureFamily: "story",
    category: "Achievement",
    context: "Impromptu",
    text: "Tell me about an end-to-end project you worked on.",
    recommendedDurationSeconds: 120,
    sector: "tech",
    company: "Google",
  },
  {
    id: "GOOG14",
    structureFamily: "rationale",
    category: "Motivation",
    context: "Impromptu",
    text: "Why Google?",
    recommendedDurationSeconds: 90,
    sector: "tech",
    company: "Google",
  },

  // ── INTERVIEW — AMAZON (Leadership Principles question bank) ────────────
  // Tagged with company + peiDimension (here, the LP name) so record.tsx can
  // prefer these over the generic tech pool when Amazon is the active
  // company. Several of these carry no corroborating candidate evidence
  // (see company_knowledge_base.json — evidenceCount: 0 entries) and are
  // included only as practice prompts covering all 16 Leadership Principles,
  // not as a claim that Amazon actually asks this specific wording — the
  // product never asserts verbatim accuracy for any company's questions.
  {
    id: "AMZ1",
    structureFamily: "story",
    category: "Customer Obsession",
    context: "Impromptu",
    text: "Tell me about a time you dealt with a difficult customer.",
    recommendedDurationSeconds: 120,
    sector: "tech",
    company: "Amazon",
    peiDimension: "Customer Obsession",
  },
  {
    id: "AMZ2",
    structureFamily: "story",
    category: "Ownership",
    context: "Impromptu",
    text: "Tell me about a time you had to make a decision without your manager.",
    recommendedDurationSeconds: 120,
    sector: "tech",
    company: "Amazon",
    peiDimension: "Ownership",
  },
  {
    id: "AMZ3",
    structureFamily: "story",
    category: "Invent and Simplify",
    context: "Impromptu",
    text: "Tell me about a time you simplified a complex business question.",
    recommendedDurationSeconds: 120,
    sector: "tech",
    company: "Amazon",
    peiDimension: "Invent and Simplify",
  },
  {
    id: "AMZ4",
    structureFamily: "story",
    category: "Are Right, A Lot",
    context: "Impromptu",
    text: "Tell me about a time you made an important decision with incomplete information. How did you decide, and how did it turn out?",
    recommendedDurationSeconds: 120,
    sector: "tech",
    company: "Amazon",
    peiDimension: "Are Right, A Lot",
  },
  {
    id: "AMZ5",
    structureFamily: "story",
    category: "Learn and Be Curious",
    context: "Impromptu",
    text: "Tell me about a time you learned something on your own out of curiosity.",
    recommendedDurationSeconds: 120,
    sector: "tech",
    company: "Amazon",
    peiDimension: "Learn and Be Curious",
  },
  {
    id: "AMZ6",
    structureFamily: "story",
    category: "Hire and Develop the Best",
    context: "Impromptu",
    text: "Tell me about a time you hired the wrong person, or realized a hiring decision was a mistake.",
    recommendedDurationSeconds: 120,
    sector: "tech",
    company: "Amazon",
    peiDimension: "Hire and Develop the Best",
  },
  {
    id: "AMZ7",
    structureFamily: "story",
    category: "Insist on the Highest Standards",
    context: "Impromptu",
    text: "Tell me about a time you identified a problem or process that needed improvement. What did you do, and what was the measurable result?",
    recommendedDurationSeconds: 120,
    sector: "tech",
    company: "Amazon",
    peiDimension: "Insist on the Highest Standards",
  },
  {
    id: "AMZ8",
    structureFamily: "story",
    category: "Think Big",
    context: "Impromptu",
    text: "Tell me about a time you proposed a significantly bigger or bolder direction than what was originally planned. How did you get others on board?",
    recommendedDurationSeconds: 120,
    sector: "tech",
    company: "Amazon",
    peiDimension: "Think Big",
  },
  {
    id: "AMZ9",
    structureFamily: "story",
    category: "Bias for Action",
    context: "Impromptu",
    text: "Tell me about a time you had to act quickly without all the data you wanted. What was the risk, and how did you manage it?",
    recommendedDurationSeconds: 120,
    sector: "tech",
    company: "Amazon",
    peiDimension: "Bias for Action",
  },
  {
    id: "AMZ10",
    structureFamily: "story",
    category: "Frugality",
    context: "Impromptu",
    text: "Tell me about a time you delivered a result with far fewer resources, budget, or headcount than you would have liked.",
    recommendedDurationSeconds: 120,
    sector: "tech",
    company: "Amazon",
    peiDimension: "Frugality",
  },
  {
    id: "AMZ11",
    structureFamily: "story",
    category: "Earn Trust",
    context: "Impromptu",
    text: "Tell me about a time you had to work with a challenging coworker.",
    recommendedDurationSeconds: 120,
    sector: "tech",
    company: "Amazon",
    peiDimension: "Earn Trust",
  },
  {
    id: "AMZ12",
    structureFamily: "story",
    category: "Dive Deep",
    context: "Impromptu",
    text: "Tell me about a time a metric or report didn't match what you were seeing on the ground. How did you get to the root cause?",
    recommendedDurationSeconds: 120,
    sector: "tech",
    company: "Amazon",
    peiDimension: "Dive Deep",
  },
  {
    id: "AMZ13",
    structureFamily: "story",
    category: "Have Backbone; Disagree and Commit",
    context: "Impromptu",
    text: "Describe a time where you had a difficult situation convincing your stakeholders regarding your proposal.",
    recommendedDurationSeconds: 120,
    sector: "tech",
    company: "Amazon",
    peiDimension: "Have Backbone; Disagree and Commit",
  },
  {
    id: "AMZ14",
    structureFamily: "story",
    category: "Deliver Results",
    context: "Impromptu",
    text: "Tell me about a time when you had to meet a tight deadline.",
    recommendedDurationSeconds: 120,
    sector: "tech",
    company: "Amazon",
    peiDimension: "Deliver Results",
  },
  {
    id: "AMZ15",
    structureFamily: "story",
    category: "Strive to be Earth's Best Employer",
    context: "Impromptu",
    text: "Tell me about a time you made your team's work environment safer, more inclusive, or more sustainable for the people on it.",
    recommendedDurationSeconds: 120,
    sector: "tech",
    company: "Amazon",
    peiDimension: "Strive to be Earth's Best Employer",
  },
  {
    id: "AMZ16",
    structureFamily: "story",
    category: "Success and Scale Bring Broad Responsibility",
    context: "Impromptu",
    text: "Tell me about a time you identified an unintended consequence of your work on customers, the community, or the environment. What did you do about it?",
    recommendedDurationSeconds: 120,
    sector: "tech",
    company: "Amazon",
    peiDimension: "Success and Scale Bring Broad Responsibility",
  },
  {
    id: "AMZ17",
    structureFamily: "narrative",
    category: "Introduction",
    context: "Impromptu",
    text: "Tell me about yourself.",
    recommendedDurationSeconds: 90,
    sector: "tech",
    company: "Amazon",
  },
  {
    id: "AMZ18",
    structureFamily: "narrative",
    category: "Introduction",
    context: "Impromptu",
    text: "Walk me through your resume.",
    recommendedDurationSeconds: 90,
    sector: "tech",
    company: "Amazon",
  },
  {
    id: "AMZ19",
    structureFamily: "rationale",
    category: "Motivation",
    context: "Impromptu",
    text: "Why Amazon?",
    recommendedDurationSeconds: 90,
    sector: "tech",
    company: "Amazon",
  },
  {
    id: "AMZ20",
    structureFamily: "rationale",
    category: "Self-Assessment",
    context: "Impromptu",
    text: "What is your biggest weakness?",
    recommendedDurationSeconds: 90,
    sector: "tech",
    company: "Amazon",
  },
  {
    id: "AMZ21",
    structureFamily: "rationale",
    category: "Self-Assessment",
    context: "Impromptu",
    text: "What would you say are your main strengths?",
    recommendedDurationSeconds: 90,
    sector: "tech",
    company: "Amazon",
  },

  // ── INTERVIEW — GENERAL & OTHER SECTORS ───────────────────────────────────

  {
    id: "G1",
    structureFamily: "rationale",
    category: "Motivation",
    context: "Impromptu",
    text: "Why this organization? What is it about the mission or work that brings you here specifically?",
    recommendedDurationSeconds: 90,
    sector: "general",
  },
  {
    id: "G2",
    structureFamily: "story",
    category: "Leadership",
    context: "Impromptu",
    text: "Tell me about a time you demonstrated leadership — formal or informal. What did you do and what was the outcome?",
    recommendedDurationSeconds: 120,
    sector: "general",
  },
  {
    id: "G3",
    structureFamily: "story",
    category: "Teamwork",
    context: "Impromptu",
    text: "Tell me about a time you worked effectively as part of a team with people very different from you. What was your role and contribution?",
    recommendedDurationSeconds: 120,
    sector: "general",
  },
  {
    id: "G4",
    structureFamily: "story",
    category: "Communication",
    context: "Impromptu",
    text: "Tell me about a time you had to communicate something complex to a non-specialist audience.",
    recommendedDurationSeconds: 120,
    sector: "general",
  },
  {
    id: "G5",
    structureFamily: "story",
    category: "Resilience",
    context: "Impromptu",
    text: "Tell me about a time you had to manage a significant challenge or setback. How did you respond?",
    recommendedDurationSeconds: 120,
    sector: "general",
  },
  {
    id: "G6",
    structureFamily: "story",
    category: "Initiative",
    context: "Impromptu",
    text: "Tell me about a time you identified an opportunity to improve something — a process, an outcome, a relationship — and acted on it.",
    recommendedDurationSeconds: 120,
    sector: "general",
  },
  {
    id: "G7",
    structureFamily: "story",
    category: "Pressure",
    context: "Impromptu",
    text: "Tell me about a time you had to balance competing priorities under pressure. How did you decide what mattered most?",
    recommendedDurationSeconds: 120,
    sector: "general",
  },
  {
    id: "G8",
    structureFamily: "story",
    category: "Adaptability",
    context: "Impromptu",
    text: "Tell me about a time you had to deliver with limited resources, support, or guidance.",
    recommendedDurationSeconds: 120,
    sector: "general",
  },
  {
    id: "G9",
    structureFamily: "story",
    category: "Influence",
    context: "Impromptu",
    text: "Tell me about a time you had to bring people with very different perspectives toward a shared outcome.",
    recommendedDurationSeconds: 120,
    sector: "general",
  },
  {
    id: "G10",
    structureFamily: "story",
    category: "Values",
    context: "Impromptu",
    text: "Tell me about a time you had to make a decision that involved a values or integrity tension. What did you do?",
    recommendedDurationSeconds: 120,
    sector: "general",
  },
];

export function getPromptContext(promptText: string): string | undefined {
  return PROMPTS.find(p => p.text === promptText)?.context;
}

// Fallback classification for prompts that aren't in the curated list —
// custom typed-in prompts, and the onboarding baseline prompts (which use
// their own wording and don't appear in PROMPTS verbatim). Deliberately
// conservative: unmatched text returns undefined, which leaves the scoring
// model on its existing generic structure guidance rather than guessing.
const FALLBACK_PATTERNS: Array<{ re: RegExp; family: StructureFamily }> = [
  { re: /tell me about yourself|walk me through your background|introduce yourself|tell me about your journey/i, family: "narrative" },
  { re: /walk me through a project|project (that )?you.?re (currently )?working on/i, family: "narrative" },
  { re: /what does success look like|where do you want to be(,| )?professionally/i, family: "vision" },
  { re: /^why (do you|are you|this)|^what is your (greatest )?weakness|^how do you use/i, family: "rationale" },
  { re: /tell me about a time|describe a (situation|time)/i, family: "story" },
];

export function getPromptStructureFamily(promptText: string): StructureFamily | undefined {
  const listed = PROMPTS.find(p => p.text === promptText)?.structureFamily;
  if (listed) return listed;
  const trimmed = promptText.trim();
  return FALLBACK_PATTERNS.find(p => p.re.test(trimmed))?.family;
}

const router = Router();

router.get("/v1/prompts", requireAuth, (req, res) => {
  const { category, sector } = req.query;
  let prompts = PROMPTS;
  if (category) prompts = prompts.filter(p => p.category === category);
  if (sector) prompts = prompts.filter(p => p.sector === sector || p.sector === "all");
  res.json({ prompts });
});

router.get("/v1/prompts/random", requireAuth, (req, res) => {
  const { category, sector } = req.query;
  let pool = PROMPTS;
  if (category) pool = pool.filter(p => p.category === category);
  if (sector) pool = pool.filter(p => p.sector === sector || p.sector === "all");
  const prompt = pool[Math.floor(Math.random() * pool.length)];
  res.json(prompt);
});

export default router;
